name: Code Coverage Summary Report

# Triggers the workflow on push or pull request events on any of the branches
on: push
    
jobs:
  # This workflow contains a single job called build
 build:
    # The type of runner that the job will run on ubuntu OS
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm install

      # Using the Code Coverage Action from https://github.com/marketplace/actions/code-coverage-summary
      - name: Code Coverage Summary
        run: npm run coverage

